# Generated by Django 2.2.2 on 2019-06-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaways', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giveaway',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='_giveaway_participants_+', to='users.DiscordUser'),
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='winners',
            field=models.ManyToManyField(blank=True, related_name='_giveaway_winners_+', to='users.DiscordUser'),
        ),
    ]
