# Generated by Django 2.2.2 on 2019-06-25 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('giveaways', '0002_auto_20190624_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giveaway',
            name='winners',
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='success',
            field=models.BooleanField(help_text='• Yes: Giveaway happened successfully.<br/>• No: Giveaway failed due to a Discord exception.<br/>• Unknown: Giveaway happening.', null=True),
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.PositiveIntegerField()),
                ('nonce', models.PositiveIntegerField()),
                ('giveaway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='giveaways.Giveaway')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='users.DiscordUser')),
            ],
        ),
    ]
