# Generated by Django 2.2.2 on 2019-06-25 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giveaways', '0003_auto_20190625_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winner',
            old_name='result',
            new_name='index',
        ),
    ]
