# Generated by Django 2.2.2 on 2019-06-26 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giveaways', '0004_auto_20190625_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giveaway',
            old_name='ended_at',
            new_name='ending_at',
        ),
    ]
