# Generated by Django 2.2.2 on 2019-06-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaways', '0005_auto_20190626_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='giveaway',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
